<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<table width="100%" height="100%" style="z-index:2;position:absolute;display:none;border:none;" id="doing_alert">
<tr><td></td></tr>
<tr><td width="30%"></td>
	<td width="40%" height="45" align="center" bgcolor="#ccccff" style="border:none;">程序执行中，请稍等片刻......</td>
	<td width="30%"></td></tr>
<tr><td></td></tr>
</table>
<script language="JavaScript">
function doing(){
	window.doing_alert.style.display='block';
}

</script>
